version: ´3.8´

services:
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    container_name: postgres
      
  redis:
    image: redis
    container_name: redis
    
  backend:
    image: back
    ports:
    - 8080:8080
    environment:
    - REQUEST_ORIGIN=http://localhost:5000
    - REDIS_HOST=redis
    - POSTGRES_HOST=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DATABASE=postgres
    
    depends_on:
      - postgres
      - redis

  frontend:
    image: front
    ports:
    - 5000:5000

