version: ´3.8´

services:
  redis:
    image: redis
    container_name: redis
    
  backend:
    image: back
    ports:
    - 8080:8080
    environment:
    - REQUEST_ORIGIN=http://localhost:5000
    - REDIS_HOST=redis

  frontend:
    image: front
    ports:
    - 5000:5000

